# Generated by Django 5.1.6 on 2025-03-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='desired_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='desired_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
